# Generated by Django 5.0.6 on 2024-06-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_availableterm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availableterm',
            name='term',
        ),
    ]
