# Generated by Django 5.0.6 on 2024-06-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_availableterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableterm',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='availableterm',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
